In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv(r"C:\Users\Rohit\Desktop\medAI\dataset\Symptom2Disease.csv")

In [3]:
data

      Unnamed: 0      label                                               text
0              0  Psoriasis  I have been experiencing a skin rash on my arm...
1              1  Psoriasis  My skin has been peeling, especially on my kne...
2              2  Psoriasis  I have been experiencing joint pain in my fing...
3              3  Psoriasis  There is a silver like dusting on my skin, esp...
4              4  Psoriasis  My nails have small dents or pits in them, and...
...          ...        ...                                                ...
1195         295   diabetes  I'm shaking and trembling all over. I've lost ...
1196         296   diabetes  Particularly in the crevices of my skin, I hav...
1197         297   diabetes  I regularly experience these intense urges and...
1198         298   diabetes  I have trouble breathing, especially outside. ...
1199         299   diabetes  I constantly sneeze and have a dry cough. My i...

[1200 rows x 3 columns]

In [7]:
data.describe()

        Unnamed: 0
count  1200.000000
mean    149.500000
std      86.638166
min       0.000000
25%      74.750000
50%     149.500000
75%     224.250000
max     299.000000

In [8]:
data.tail()

      Unnamed: 0     label                                               text
1195         295  diabetes  I'm shaking and trembling all over. I've lost ...
1196         296  diabetes  Particularly in the crevices of my skin, I hav...
1197         297  diabetes  I regularly experience these intense urges and...
1198         298  diabetes  I have trouble breathing, especially outside. ...
1199         299  diabetes  I constantly sneeze and have a dry cough. My i...

Text normalisation function

In [17]:
import re

def normalize_text(text):
    text = text.lower()
    
    # remove special characters
    text = re.sub(r'[^a-z\s]', '', text)
    
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # remove stopwords properly (word-based)
    stop_words = ["i", "have", "am", "feel", "since", "for", 
                  "been", "having", "from", "the", "an"]
    
    words = text.split()
    words = [w for w in words if w not in stop_words]
    text = " ".join(words)
    
    # synonym replacement
    replacements = {
        "stomach ache": "abdominal pain",
        "tummy pain": "abdominal pain",
        "high temperature": "fever",
        "breathlessness": "breathing difficulty",
        "head ache": "headache",
        "vomitting": "vomiting"
    }
    
    for key, value in replacements.items():
        text = text.replace(key, value)
    
    # normalize severity
    text = text.replace("high fever", "fever")
    text = text.replace("mild fever", "fever")
    text = text.replace("severe headache", "headache")
    
    return text

In [18]:
data["newText"]= data["text"].apply(normalize_text)

In [19]:
data.head()

,Unnamed: 0,label,text,newText
0,0,Psoriasis,I have been experiencing a skin rash on my arm...,experiencing a skin rash on my arms legs and t...
1,1,Psoriasis,"My skin has been peeling, especially on my kne...",my skin has peeling especially on my knees elb...
2,2,Psoriasis,I have been experiencing joint pain in my fing...,experiencing joint pain in my fingers wrists a...
3,3,Psoriasis,"There is a silver like dusting on my skin, esp...",there is a silver like dusting on my skin espe...
4,4,Psoriasis,"My nails have small dents or pits in them, and...",my nails small dents or pits in them and they ...

In [22]:
all_text = " ".join(data['newText'])
words = all_text.split()

In [23]:
from collections import Counter

word_counts = Counter(words)

In [28]:
print(word_counts.most_common(500))

[('and', 2609), ('my', 1859), ('a', 1266), ('ive', 669), ('of', 533), ('to', 518), ('is', 505), ('in', 435), ('has', 432), ('also', 418), ('skin', 382), ('lot', 353), ('are', 349), ('really', 331), ('pain', 320), ('fever', 272), ('it', 271), ('on', 269), ('im', 258), ('with', 244), ('that', 224), ('me', 224), ('feeling', 217), ('experiencing', 208), ('neck', 178), ('there', 155), ('all', 155), ('had', 152), ('its', 148), ('cough', 148), ('when', 147), ('chest', 147), ('get', 147), ('as', 145), ('quite', 139), ('headache', 134), ('up', 131), ('throat', 131), ('rash', 129), ('hurts', 129), ('red', 114), ('body', 109), ('some', 106), ('severe', 105), ('itching', 105), ('or', 101), ('this', 100), ('over', 99), ('back', 98), ('painful', 98), ('weak', 98), ('chills', 97), ('very', 96), ('difficult', 94), ('discomfort', 89), ('lost', 89), ('nausea', 88), ('like', 87), ('time', 87), ('frequently', 86), ('coughing', 86), ('uncomfortable', 85), ('muscles', 84), ('recently', 80), ('go', 79), ('occasionally', 79), ('legs', 77), ('exhausted', 77), ('vomiting', 77), ('cant', 76), ('stomach', 76), ('breathing', 75), ('appetite', 74), ('nose', 73), ('trouble', 73), ('weight', 70), ('out', 69), ('stiff', 69), ('joints', 68), ('rashes', 68), ('additionally', 68), ('arms', 67), ('swollen', 67), ('pimples', 67), ('itchy', 66), ('these', 65), ('which', 65), ('addition', 65), ('yellow', 65), ('headaches', 64), ('well', 64), ('along', 63), ('often', 62), ('extremely', 62), ('sores', 62), ('by', 60), ('at', 60), ('night', 60), ('anus', 60), ('dry', 59), ('eyes', 59), ('developed', 58), ('urine', 58), ('spots', 57), ('do', 57), ('sometimes', 57), ('indigestion', 57), ('causing', 56), ('sore', 56), ('dizziness', 56), ('because', 55), ('muscle', 54), ('weakness', 53), ('tired', 52), ('become', 52), ('lately', 52), ('about', 51), ('face', 51), ('hard', 51), ('around', 50), ('issues', 50), ('blackheads', 50), ('few', 48), ('heart', 48), ('difficulty', 47), ('suffering', 47), ('worse', 46), ('more', 46), ('feels', 46), ('abdominal', 46), ('phlegm', 46), ('pee', 46), ('after', 45), ('making', 45), ('dont', 45), ('blood', 45), ('walking', 45), ('ache', 45), ('perspiring', 45), ('balance', 45), ('days', 44), ('intense', 44), ('getting', 44), ('problems', 44), ('mouth', 43), ('sick', 43), ('sweating', 43), ('little', 42), ('seem', 42), ('eating', 42), ('vision', 42), ('anything', 41), ('frequent', 41), ('noticed', 40), ('symptoms', 40), ('high', 40), ('dark', 38), ('mucus', 38), ('different', 37), ('thick', 37), ('constipation', 37), ('persistent', 37), ('so', 37), ('worn', 37), ('acid', 37), ('taste', 37), ('accompanied', 36), ('move', 36), ('breath', 36), ('be', 35), ('day', 35), ('smell', 35), ('small', 34), ('just', 34), ('constantly', 34), ('especially', 33), ('now', 33), ('excessive', 33), ('pusfilled', 33), ('too', 32), ('bloody', 32), ('dizzy', 32), ('reflux', 32), ('visual', 32), ('becoming', 31), ('bad', 31), ('temperature', 30), ('not', 30), ('aches', 30), ('rest', 30), ('scratchy', 30), ('urinate', 30), ('them', 29), ('walk', 29), ('terrible', 29), ('bothering', 29), ('patches', 28), ('loss', 28), ('bumps', 28), ('without', 28), ('food', 28), ('strong', 27), ('than', 27), ('worried', 27), ('regularly', 27), ('fatigued', 27), ('always', 27), ('both', 27), ('hunger', 27), ('inflamed', 26), ('fatigue', 26), ('cramps', 26), ('swelling', 26), ('stool', 26), ('heartburn', 26), ('even', 25), ('starting', 25), ('constant', 25), ('every', 25), ('turned', 25), ('challenging', 25), ('racing', 25), ('black', 25), ('bowel', 25), ('burning', 24), ('going', 24), ('but', 24), ('near', 24), ('away', 24), ('head', 24), ('concentrate', 23), ('sneezing', 23), ('irritability', 23), ('unpleasant', 22), ('can', 22), ('veins', 22), ('while', 22), ('vomit', 22), ('down', 22), ('ill', 22), ('focus', 22), ('mucous', 22), ('mucoid', 22), ('losing', 22), ('blurred', 22), ('disturbance', 22), ('sensation', 21), ('regular', 21), ('experience', 21), ('brownish', 21), ('stiffness', 21), ('sour', 21), ('off', 20), ('they', 20), ('touch', 20), ('what', 20), ('experienced', 20), ('abdomen', 20), ('started', 20), ('calves', 20), ('feet', 20), ('eat', 20), ('pressure', 20), ('stools', 20), ('nodes', 20), ('makes', 20), ('lumps', 20), ('sputum', 20), ('struggling', 20), ('restroom', 20), ('past', 19), ('sensitive', 19), ('strange', 19), ('irritated', 19), ('areas', 19), ('hurt', 19), ('extreme', 19), ('nauseous', 19), ('area', 19), ('result', 19), ('wont', 19), ('nasty', 19), ('bathroom', 19), ('morning', 19), ('distorted', 19), ('depression', 19), ('urges', 19), ('swallowing', 19), ('gets', 18), ('nails', 18), ('energy', 18), ('no', 18), ('diarrhea', 18), ('pus', 18), ('exhaustion', 18), ('scurrying', 18), ('increased', 18), ('lightheaded', 18), ('find', 17), ('sleeping', 17), ('infections', 17), ('spreading', 17), ('run', 17), ('health', 17), ('difficulties', 17), ('times', 17), ('lymph', 17), ('uneasy', 17), ('hurting', 17), ('sinuses', 17), ('tight', 17), ('itchiness', 17), ('low', 17), ('covered', 16), ('joint', 16), ('including', 16), ('due', 16), ('belly', 16), ('stop', 16), ('excruciatingly', 16), ('everything', 16), ('tingling', 16), ('acidic', 16), ('lack', 15), ('moreover', 15), ('pretty', 15), ('long', 15), ('several', 15), ('pains', 15), ('lips', 15), ('hue', 15), ('cold', 15), ('things', 15), ('filled', 15), ('bleeding', 15), ('then', 15), ('upper', 15), ('peeling', 14), ('itch', 14), ('developing', 14), ('seems', 14), ('behind', 14), ('deal', 14), ('using', 14), ('rather', 14), ('felt', 14), ('producing', 14), ('queasy', 14), ('made', 13), ('noticeable', 13), ('keep', 13), ('healing', 13), ('discomforts', 13), ('periods', 13), ('last', 13), ('staying', 13), ('fluid', 13), ('work', 13), ('during', 13), ('entire', 13), ('resemble', 13), ('color', 13), ('dents', 12), ('use', 12), ('sleep', 12), ('flaky', 12), ('irritating', 12), ('seen', 12), ('excruciating', 12), ('know', 12), ('vessels', 12), ('activities', 12), ('swell', 12), ('through', 12), ('bloating', 12), ('much', 12), ('generally', 12), ('scratching', 12), ('lesions', 12), ('running', 12), ('incredibly', 12), ('certain', 12), ('look', 12), ('rashy', 12), ('breathe', 12), ('muscular', 12), ('catch', 12), ('constipated', 12), ('start', 12), ('aftertaste', 12), ('elbows', 11), ('concerning', 11), ('if', 11), ('got', 11), ('change', 11), ('observed', 11), ('any', 11), ('into', 11), ('suddenly', 11), ('coming', 11), ('itches', 11), ('runny', 11), ('unwell', 11), ('awful', 11), ('only', 11), ('woke', 11), ('dealing', 11), ('chronic', 11), ('unsteady', 11), ('acidity', 11), ('meals', 11), ('impatience', 11), ('almost', 11), ('smells', 11), ('knees', 10), ('parts', 10), ('usual', 10), ('longer', 10), ('most', 10), ('such', 10), ('shivering', 10), ('everywhere', 10), ('bloated', 10), ('bothered', 10), ('beating', 10), ('profusely', 10), ('foul', 10), ('motions', 10), ('movements', 10), ('whenever', 10), ('scurring', 10), ('horrible', 10), ('impaired', 10), ('focusing', 10), ('eyesight', 10), ('hungry', 10), ('limb', 10), ('belching', 10), ('foods', 10), ('foggy', 10), ('lose', 10), ('changes', 9), ('sudden', 9), ('other', 9), ('prone', 9), ('bleeds', 9), ('miserable', 9), ('something', 9), ('particularly', 9), ('significant', 9), ('asleep', 9), ('see', 9), ('cannot', 9), ('believe', 9), ('gotten', 9), ('large', 9), ('daily', 9), ('think', 9), ('week', 9), ('able', 9), ('watery', 9), ('theres', 9), ('thats', 9), ('myself', 9), ('throughout', 9), ('appear', 9), ('was', 9), ('kind', 9), ('bumpy', 9), ('congested', 9), ('usually', 9), ('chilly', 9), ('shortness', 9), ('soreness', 9), ('butt', 9), ('ability', 9), ('numbness', 9), ('throwing', 9), ('hands', 9), ('palpitations', 9), ('lower', 8), ('flake', 8), ('peel', 8), ('life', 8), ('concerned', 8), ('visible', 8), ('causes', 8), ('tough', 8), ('sure', 8), ('mild', 8), ('urge', 8), ('rapidly', 8), ('blistering', 8), ('infection', 8), ('doctor', 8), ('odd', 8), ('balls', 8), ('colour', 8), ('drained', 8), ('simply', 8)]

In [29]:
important_words = [
    "pain", "fever", "cough", "headache", "nausea", "vomiting",
    "dizziness", "fatigue", "chills", "sweating", "weakness",
    
    "chest", "breathing", "difficulty", "blood",
    
    "throat", "abdominal", "stomach", "back", "neck",
    "joints", "muscles", "eyes", "nose", "mouth",
    
    "rash", "itching", "swollen", "red", "pimples", "spots",
    
    "urine", "diarrhea", "constipation", "appetite", "indigestion",
    
    "cold", "sore", "burning", "cramps", "swelling", "phlegm", "numbness"
]

In [30]:
def keep_medical_terms(text):
    words = text.split()
    filtered = [w for w in words if w in important_words]
    return " ".join(filtered)

In [35]:
data['newText'] = data['newText'].apply(keep_medical_terms)

In [36]:
data.head()

,Unnamed: 0,label,text,newText
0,0,Psoriasis,I have been experiencing a skin rash on my arm...,rash red
1,1,Psoriasis,"My skin has been peeling, especially on my kne...",burning
2,2,Psoriasis,I have been experiencing joint pain in my fing...,pain pain joints
3,3,Psoriasis,"There is a silver like dusting on my skin, esp...",back
4,4,Psoriasis,"My nails have small dents or pits in them, and...",

In [42]:
data.loc[3, "text"]

'There is a silver like dusting on my skin, especially on my lower back and scalp. This dusting is made up of small scales that flake off easily when I scratch them.'

In [47]:
data.head()

,Unnamed: 0,label,text,newText
0,0,Psoriasis,I have been experiencing a skin rash on my arm...,rash red
1,1,Psoriasis,"My skin has been peeling, especially on my kne...",burning
2,2,Psoriasis,I have been experiencing joint pain in my fing...,pain pain joints
3,3,Psoriasis,"There is a silver like dusting on my skin, esp...",back
4,4,Psoriasis,"My nails have small dents or pits in them, and...",

In [65]:
# Recreate X
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data['newText'])

# Recreate y (IMPORTANT)
y = data['label']

# Split again
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [67]:

print(type(data["label"]))

<class 'pandas.core.series.Series'>

In [68]:

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [69]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7208333333333333

In [85]:
import numpy as np

def predict_disease(text):
    text = normalize_text(text)
    text = merge_phrases(text)
    text = keep_medical_terms(text)
    
    vec = vectorizer.transform([text])
    
    probs = model.predict_proba(vec)[0]
    
    # sort probabilities
    sorted_idx = np.argsort(probs)[::-1]
    
    top1 = sorted_idx[0]
    top2 = sorted_idx[1]
    
    # confidence difference
    diff = probs[top1] - probs[top2]
    
    # threshold decision
    if diff > 0.2:
        return [model.classes_[top1]]   # only 1 disease
    else:
        return [model.classes_[top1], model.classes_[top2]]  # return 2

In [86]:
# def get_urgency(text):
#     if any(x in text for x in ["chestpain", "breathingdifficulty", "unconscious"]):
#         return "HIGH"
    
#     elif any(x in text for x in ["fever", "vomiting", "headache"]):
#         return "MEDIUM"
    
#     else:
#         return "LOW"

In [87]:
def get_urgency(text):
    # HIGH RISK
    if any(x in text for x in [
        "chest pain", "chestpain",
        "breathing difficulty", "breathingdifficulty",
        "difficulty breathing",
        "unconscious", "blood"
    ]):
        return "HIGH"
    
    # MEDIUM
    elif any(x in text for x in [
        "fever", "vomiting", "headache"
    ]):
        return "MEDIUM"
    
    else:
        return "LOW"

In [88]:
def get_advice(urgency):
    if urgency == "HIGH":
        return "Go to hospital immediately"
    elif urgency == "MEDIUM":
        return "Consult a doctor soon"
    else:
        return "Rest and monitor symptoms"

In [89]:
def triage_system(user_input):
    clean = normalize_text(user_input)
    clean = merge_phrases(clean)
    clean = keep_medical_terms(clean)
    
    diseases = predict_disease(user_input)
    urgency = get_urgency(clean)
    advice = get_advice(urgency)
    
    return {
        "symptoms": clean,
        "diseases": diseases,
        "urgency": urgency,
        "advice": advice
    }

In [90]:
triage_system("I have chest pain and difficulty breathing")

{'symptoms': 'chest pain difficulty breathing',
 'diseases': ['drug reaction', 'Pneumonia'],
 'urgency': 'HIGH',
 'advice': 'Go to hospital immediately'}

In [91]:
triage_system("vomiting blood and weakness")

{'symptoms': 'vomiting blood weakness',
 'diseases': ['urinary tract infection', 'Dimorphic Hemorrhoids'],
 'urgency': 'HIGH',
 'advice': 'Go to hospital immediately'}

In [92]:
triage_system("vomiting and nausea for two days")

{'symptoms': 'vomiting nausea',
 'diseases': ['Malaria'],
 'urgency': 'MEDIUM',
 'advice': 'Consult a doctor soon'}

In [93]:
triage_system("I have mild cough and cold")

{'symptoms': 'cough cold',
 'diseases': ['Common Cold', 'Pneumonia'],
 'urgency': 'LOW',
 'advice': 'Rest and monitor symptoms'}